/* Mock VFX catalog — stands in for /api/vfx/catalog while prototyping.
   previewType drives the procedural animated preview. */
window.VFX_CATALOG = {
  version: 1,
  lastUpdated: '2026-05-28T10:00:00Z',
  categories: [
    'RPG/Hit', 'RPG/Buff', 'RPG/Skill', 'RPG/Heal',
    'Explosion', 'Fire', 'Magic/Arcane', 'Magic/Lightning',
    'Environment/Smoke', 'Environment/Portal', 'UI/Coin', 'Slash',
  ],
  items: [
    { id: 'fx_001', name: 'Crit Hit Spark',        category: 'RPG/Hit',          previewType: 'slash',     particleCount: 64,   fileSize: 184320,  uploadedAt: '2026-05-26T09:12:00Z', uploadedBy: 'Mai Tran',   dependencies: ['Shader: Additive', 'Texture: spark_atlas'], featured: true },
    { id: 'fx_002', name: 'Heavy Impact',          category: 'RPG/Hit',          previewType: 'explosion', particleCount: 220,  fileSize: 512000,  uploadedAt: '2026-05-24T14:00:00Z', uploadedBy: 'Khoa Le',    dependencies: ['Shader: Additive'] },
    { id: 'fx_003', name: 'Holy Heal Burst',       category: 'RPG/Heal',         previewType: 'heal',      particleCount: 140,  fileSize: 327680,  uploadedAt: '2026-05-22T08:30:00Z', uploadedBy: 'Mai Tran',   dependencies: ['Texture: ring_soft', 'Mesh: quad'] },
    { id: 'fx_004', name: 'Power Up Aura',         category: 'RPG/Buff',         previewType: 'buff',      particleCount: 90,   fileSize: 245760,  uploadedAt: '2026-05-20T11:45:00Z', uploadedBy: 'Linh Pham',  dependencies: [] },
    { id: 'fx_005', name: 'Fireball Cast',         category: 'Fire',             previewType: 'fire',      particleCount: 310,  fileSize: 768000,  uploadedAt: '2026-05-28T07:05:00Z', uploadedBy: 'Khoa Le',    dependencies: ['Shader: Additive', 'Texture: flame_atlas', 'Light: point'], featured: true },
    { id: 'fx_006', name: 'Ember Trail',           category: 'Fire',             previewType: 'fire',      particleCount: 120,  fileSize: 198000,  uploadedAt: '2026-05-19T16:20:00Z', uploadedBy: 'Linh Pham',  dependencies: ['Texture: flame_atlas'] },
    { id: 'fx_007', name: 'Arcane Orb',            category: 'Magic/Arcane',     previewType: 'magic',     particleCount: 175,  fileSize: 430080,  uploadedAt: '2026-05-27T13:10:00Z', uploadedBy: 'Mai Tran',   dependencies: ['Shader: Additive', 'Texture: noise_swirl'], featured: true },
    { id: 'fx_008', name: 'Mana Shield',           category: 'Magic/Arcane',     previewType: 'buff',      particleCount: 60,   fileSize: 163840,  uploadedAt: '2026-05-15T10:00:00Z', uploadedBy: 'Khoa Le',    dependencies: ['Mesh: sphere'] },
    { id: 'fx_009', name: 'Chain Lightning',       category: 'Magic/Lightning',  previewType: 'lightning', particleCount: 88,   fileSize: 276480,  uploadedAt: '2026-05-25T09:40:00Z', uploadedBy: 'Linh Pham',  dependencies: ['Shader: Additive', 'Texture: bolt'] },
    { id: 'fx_010', name: 'Static Discharge',      category: 'Magic/Lightning',  previewType: 'lightning', particleCount: 130,  fileSize: 358400,  uploadedAt: '2026-05-12T15:30:00Z', uploadedBy: 'Mai Tran',   dependencies: ['Texture: bolt'] },
    { id: 'fx_011', name: 'Big Boom',              category: 'Explosion',        previewType: 'explosion', particleCount: 420,  fileSize: 1048576, uploadedAt: '2026-05-23T12:00:00Z', uploadedBy: 'Khoa Le',    dependencies: ['Shader: Additive', 'Texture: smoke_puff', 'Light: point'], featured: true },
    { id: 'fx_012', name: 'Grenade Pop',           category: 'Explosion',        previewType: 'explosion', particleCount: 260,  fileSize: 614400,  uploadedAt: '2026-05-10T09:00:00Z', uploadedBy: 'Linh Pham',  dependencies: ['Texture: smoke_puff'] },
    { id: 'fx_013', name: 'Drift Smoke',           category: 'Environment/Smoke',previewType: 'smoke',     particleCount: 80,   fileSize: 204800,  uploadedAt: '2026-05-18T08:15:00Z', uploadedBy: 'Mai Tran',   dependencies: ['Texture: smoke_soft'] },
    { id: 'fx_014', name: 'Campfire Smoke',        category: 'Environment/Smoke',previewType: 'smoke',     particleCount: 55,   fileSize: 153600,  uploadedAt: '2026-05-08T17:50:00Z', uploadedBy: 'Khoa Le',    dependencies: [] },
    { id: 'fx_015', name: 'Summon Portal',         category: 'Environment/Portal',previewType: 'magic',    particleCount: 290,  fileSize: 880000,  uploadedAt: '2026-05-29T06:30:00Z', uploadedBy: 'Linh Pham',  dependencies: ['Shader: Additive', 'Texture: noise_swirl', 'Mesh: torus'], featured: true },
    { id: 'fx_016', name: 'Rift Tear',             category: 'Environment/Portal',previewType: 'lightning',particleCount: 110,  fileSize: 296960,  uploadedAt: '2026-05-14T11:20:00Z', uploadedBy: 'Mai Tran',   dependencies: ['Texture: bolt'] },
    { id: 'fx_017', name: 'Coin Pickup',           category: 'UI/Coin',          previewType: 'coin',      particleCount: 24,   fileSize: 81920,   uploadedAt: '2026-05-21T10:10:00Z', uploadedBy: 'Khoa Le',    dependencies: ['Texture: coin_atlas'] },
    { id: 'fx_018', name: 'Reward Shower',         category: 'UI/Coin',          previewType: 'coin',      particleCount: 150,  fileSize: 389120,  uploadedAt: '2026-05-11T13:00:00Z', uploadedBy: 'Linh Pham',  dependencies: ['Texture: coin_atlas'] },
    { id: 'fx_019', name: 'Blade Slash',           category: 'Slash',            previewType: 'slash',     particleCount: 40,   fileSize: 122880,  uploadedAt: '2026-05-17T09:25:00Z', uploadedBy: 'Mai Tran',   dependencies: ['Texture: slash_arc'] },
    { id: 'fx_020', name: 'Whirlwind Cut',         category: 'Slash',            previewType: 'slash',     particleCount: 72,   fileSize: 215040,  uploadedAt: '2026-05-09T16:00:00Z', uploadedBy: 'Khoa Le',    dependencies: ['Texture: slash_arc', 'Mesh: ribbon'] },
    { id: 'fx_021', name: 'Frost Nova',            category: 'Magic/Arcane',     previewType: 'explosion', particleCount: 200,  fileSize: 471040,  uploadedAt: '2026-05-13T08:40:00Z', uploadedBy: 'Linh Pham',  dependencies: ['Shader: Additive', 'Texture: ice_shard'] },
    { id: 'fx_022', name: 'Level Up Ring',         category: 'RPG/Buff',         previewType: 'buff',      particleCount: 100,  fileSize: 256000,  uploadedAt: '2026-05-27T18:00:00Z', uploadedBy: 'Mai Tran',   dependencies: ['Texture: ring_soft'] },
    { id: 'fx_023', name: 'Dragon Breath',         category: 'Fire',             previewType: 'fire',      particleCount: 380,  fileSize: 960000,  uploadedAt: '2026-05-16T10:30:00Z', uploadedBy: 'Khoa Le',    dependencies: ['Shader: Additive', 'Texture: flame_atlas', 'Light: point'] },
    { id: 'fx_024', name: 'Sword Combo',           category: 'RPG/Skill',        previewType: 'slash',     particleCount: 95,   fileSize: 287000,  uploadedAt: '2026-05-07T12:45:00Z', uploadedBy: 'Linh Pham',  dependencies: ['Texture: slash_arc'] },
    { id: 'fx_025', name: 'Meteor Strike',         category: 'RPG/Skill',        previewType: 'explosion', particleCount: 450,  fileSize: 1153434, uploadedAt: '2026-05-29T09:00:00Z', uploadedBy: 'Mai Tran',   dependencies: ['Shader: Additive', 'Texture: flame_atlas', 'Texture: smoke_puff', 'Light: point'] },
    { id: 'fx_026', name: 'Sparkle Trail',         category: 'UI/Coin',          previewType: 'magic',     particleCount: 50,   fileSize: 143360,  uploadedAt: '2026-05-06T08:00:00Z', uploadedBy: 'Khoa Le',    dependencies: [] },
  ],
};
